In [ ]:
import pandas as pd
import numpy as np

In [ ]:
symptoms = pd.read_csv('probability.csv', sep=';')
disease = pd.read_csv('qty.csv',  sep=';')

In [ ]:
disease

disease  количество пациентов
0               Левосторонний паратонзиллит                    26
1              Правосторонний паратонзиллит                    30
2     Двусторонний паратонзиллярный абсцесс                     9
3    Левосторонний паратонзиллярный абсцесс                   116
4   Правосторонний паратонзиллярный абсцесс                    96
5    Левосторнний парафарингиальный абсцесс                     3
6  Правосторонний парафарингиальный абсцесс                     3
7                Левосторонний парафарингит                     8
8               Правосторонний парафарингит                    12
9                                     Итого                   303

In [ ]:
symptoms

symptom  \
0                                         Недомогание   
1                                            Слабость   
2                                       Головную боль   
3                                 Отсутствие аппетита   
4                          Болезненное открывание рта   
5                                        Боль в горле   
6                             Боль при глотании слева   
7                            Боль при глотании справа   
8                                            Дисфагия   
9             Тризм жевательной мускулатуры I степени   
10          Тризм жевательной мускулатуры III степени   
11  Болезненность л/узлов в левой подчелюстной обл...   
12  Болезненность л/узлов в правой подчелюстной об...   
13                                    Асимметрия зева   
14    Смещение левой нёбной миндалины к средней линии   
15   Смещение правой нёбной миндалины к средней линии   
16                      Слизистая зева гиперемирована   
17                        Язычок мягкого нёба отёчен.   
18                    Слизистая глотки гиперемирована   
19  Отёк. инфильтрация околоминдаликовой клетчатки...   
20  Отёк. инфильтрация околоминдаликовой клетчатки...   
21                   Отёк боковой стенки глотки слева   
22                  Отёк боковой стенки глотки справа   

     Острый левостор паратонз абсцесс   Острый правостор паратонз абсцесс  \
0                              0.9700                              0.9600   
1                              0.9900                              0.9800   
2                              0.6600                              0.7300   
3                              0.7300                              0.7500   
4                              0.9300                              0.9000   
5                              0.9700                              0.9600   
6                              0.9300                              0.0100   
7                              0.0100                              0.9400   
8                              0.9600                              0.9400   
9                              0.5300                              0.6400   
10                             0.0400                              0.0200   
11                             0.7500                              0.0800   
12                             0.0300                              0.8100   
13                             0.9900                              0.9800   
14                             0.7500                              0.0001   
15                             0.0100                              0.8000   
16                             0.9800                              0.9800   
17                             0.9300                              0.8500   
18                             0.9400                              0.9000   
19                             0.6000                              0.0300   
20                             0.0001                              0.6000   
21                             0.2100                              0.0001   
22                             0.0100                              0.1200   

    Острый двухстор паратонз абсцесс  Острый левостор паратон-зиллит  \
0                             1.0000                          0.9200   
1                             1.0000                          0.9600   
2                             0.8800                          0.7600   
3                             0.8800                          0.7600   
4                             1.0000                          0.8000   
5                             1.0000                          1.0000   
6                             0.7700                          0.9600   
7                             0.7700                          0.0001   
8                             1.0000                          1.0000   
9                             0.7700                          0.6000   
10                            0.0000

In [ ]:
init_symptoms = np.random.randint(0,2, symptoms.shape[0])
print(init_symptoms)
len(init_symptoms)

[0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 0 0 0]


23

In [ ]:
probability = np.ones(disease.shape[0] - 1)
print(probability)
len(probability)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


9

In [ ]:
for i in range(len(probability)):
  for j in range(len(init_symptoms)):
    if init_symptoms[j] == 1:
      probability[i] *= symptoms.iloc[j][i + 1]
  probability[i] *= disease.iloc[i][1] / disease.iloc[9][1]
probability

array([1.10602373e-05, 6.52784792e-04, 0.00000000e+00, 1.39659406e-06,
       3.38651881e-03, 1.23762376e-11, 2.47524752e-07, 1.55247525e-07,
       2.56633663e-07])

In [ ]:
f'{disease.iloc[np.where(probability == np.max(probability))[0][0]][0]} -> with posibility of: {np.max(probability)}'

'Правосторонний паратонзиллярный абсцесс -> with posibility of: 0.0033865188118811884'